server:
  port: 8001
spring:
  application:
    name: admission-service
  cloud:
    config:
      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream