server:
  port: 7001
      
spring:
  application:
    name: log-service
  cloud:
    config:
      uri: http://localhost:8888
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream